VERSION 0.6

deps:
    FROM openjdk:17-jdk-alpine
    RUN apk add --update --no-cache maven
    COPY ../+deps .
    WORKDIR /services
    COPY ./pom.xml /services/
    RUN mvn clean install
    RUN mvn compile
    RUN mvn package

build:
    BUILD ./service1+build
    BUILD ./service2+build

all-unit-test:
    BUILD ./service1+unit-test
    BUILD ./service2+unit-test

all-docker:
    BUILD .service1+docker
    BUILD .service2+docker