VERSION 0.6
FROM ../+build

build:
    COPY pom.xml ./
    BUILD ./service1+build
    BUILD ./service2+build

all-unit-test:
    BUILD ./service1+unit-test
    BUILD ./service2+unit-test

all-docker:
    BUILD .service1+docker
    BUILD .service2+docker