VERSION 0.7

deps:
    FROM openjdk:17-jdk-alpine
    WORKDIR /services/service1
    COPY ../+deps .
    WORKDIR /service1
    COPY ./pom.xml /services/service1
    RUN mvn clean install
    RUN mvn compile
    RUN mvn package
    COPY
    RUN apk add --update --no-cache maven
    WORKDIR /java-example

build:
    FROM +deps
    COPY pom.xml ./
    COPY src src
    RUN mvn clean install
    RUN mvn package
    SAVE ARTIFACT ./target/app.jar app.jar

docker:
    COPY +build/app.jar app.jar
    RUN sh -c 'touch /app.jar'
    ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    SAVE IMAGE service1:latest